#!/bin/sh

exec bspwm &

xrdb -merge "${XDG_CONFIG_HOME}/x11/xresources" &
xsetroot -cursor_name left_ptr &
unclutter --timeout 1 --jitter 10 --ignore-buttons 2,4,5,6,7 --start-hidden &
xautolock -time 10 -locker "i3lock -u -c 282828 -e" &
feh --bg-fill --no-fehbg ~/.config/wallpaper/282828.png &
redshift -O 4500 &
picom
