shell = "/bin/zsh"

[window]
    padding = { x = 10, y = 10 }

[font]
    size = 11
    offset = { x = 0, y = 5 }
    glyph_offset = { x = 0, y = 3 }

[colors.primary]
    background = "#282828"
    foreground = "#d5c4a1"

[colors.cursor]
    text   = "#282828"
    cursor = "#d5c4a1"

[colors.normal]
    black   = "#282828"
    red     = "#fb4934"
    green   = "#b8bb26"
    yellow  = "#fabd2f"
    blue    = "#83a598"
    magenta = "#d3869b"
    cyan    = "#8ec07c"
    white   = "#d5c4a1"

[colors.bright]
    black   = "#665c54"
    red     = "#fb4934"
    green   = "#b8bb26"
    yellow  = "#fabd2f"
    blue    = "#83a598"
    magenta = "#d3869b"
    cyan    = "#8ec07c"
    white   = "#fbf1c7"

[cursor]
    style = { shape = "Block", blinking = "Always" }
    blink_interval = 500
    blink_timeout  = 0

[keyboard]
    bindings = [
        { key = "PageUp", mods = "None", action = "ScrollPageUp" },
        { key = "PageDown", mods = "None", action = "ScrollPageDown" },
    ]
